site_name: Cephfs文档
theme:
  name: material       # 必须用这个主题，所有功能原生支持
  language: zh

plugins:
  - search

# 👇 核心：列表 + 脚注 + Mermaid + 不提取标题
markdown_extensions:
  - toc:
      baselevel: 2        # 强制导航用文件名，不提取一级标题
  - tables                # 表格支持
  - nl2br                  # 换行自动转 <br>
  - attr_list              # 属性列表
  - def_list               # 定义列表（术语解释）
  - footnotes              # ✅ 脚注支持
  - admonition             # 提示框
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format